env:
  es6: true
  node: true
extends:
  - 'eslint:recommended'
  - airbnb-base
  - 'plugin:prettier/recommended'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
