env:
  es6: true
  node: true
extends:
  - airbnb-base
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - prettier/@typescript-eslint
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
  - import
rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
  no-console:
    - warn
settings:
  import/resolver:
    typescript:
      directory: .
